# Generated by Django 4.2.1 on 2023-06-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bert_sentiment', '0002_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='sentiment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
